messageSuccess: "§aYou have been teleported to a random location"
messageInGame: "§cThis command only works in game"
messageError: "§cError: Blocked by another plugin"
messageUnallowed: "§cUsing wild command is not allowed in this world"
minX: -3000
maxX: 3000
minZ: -3000
maxZ: 3000
BminX: -3000
BmaxX: 3000
BminZ: -3000
BmaxZ: 3000
allowedWorlds:
  - "world"
